#### 1.  Python数组切片, 直接获取某一列

In [15]:
import numpy as np
array_ = np.array(range(12)).reshape(3, 4)
print(array_)

print('-'*20)
ret = array_[:, 0:1]
print(type(ret))
print(ret) 

print('-'*20)
ret = array_[:, 0]
print(type(ret))
print(ret) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------
<class 'numpy.ndarray'>
[[0]
 [4]
 [8]]
--------------------
<class 'numpy.ndarray'>
[0 4 8]


#### 2. Pandas中获取某一列（对比上面）

In [13]:
import pandas as pd
df = pd.DataFrame(data=[['Alice', 'girl', 18, 171],
                        ['Bob', 'boy', 19, 172],
                        ['Tom', 'boy', 17, 173],
                        ['Lucy', 'girl', 18, 172]],
                  columns=['Name', 'Sex', 'Age', 'Class'],
                  index=['A', 'B', 'C', 'D'])
print(df.ix[:2, ['Age']])
print('-'*20)
print(df.ix[:2, 'Age'])

   Age
A   18
B   19
--------------------
A    18
B    19
Name: Age, dtype: int64


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:8: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


#### 3. Python枚举

In [20]:
import string
print(dict(enumerate(string.ascii_uppercase[:5], 1)))  # 支持传入开始位置

{1: 'A', 2: 'B', 3: 'C', 4: 'D', 5: 'E'}
